service: serverless-slinker
app: slinker-dev
tenant: superfly72

provider:
  name: aws
  runtime: nodejs4.3
  memorySize: 512 # optional, in MB, default is 1024
  timeout: 10 # optional, in seconds, default is 6
  versionFunctions: false # optional, default is true

plugins:
  - serverless-dynamodb-local

functions:
  createSlink:
    handler: handler.create
    events:
      - http:
          path: slink
          method: post
  retrieveSlink:
    handler: handler.get
    events:
      - http:
          path: slink/{id}
          method: get


